### ISSUE TITLE
Figure out why dependabot pull requests fail CI

### ISSUE THREAD

**Issue by timabbott** [zulip/github-actions-zulip#10]

**Comment by ggrossetie** [comment]
That's because the dist file changed (because the dependencies were updated).
I'm using `[ -z "$(git status --porcelain)" ];` to make sure that `dist/index.js` is not outdated (compared to `index.js`).

Having said that, it's a bit problematic... but I still want to make sure that `dist/index.js` was correctly generated.
I guess we could disable this check if the author is dependabot? But then we would need to remember to update `dist/index.js` before releasing otherwise the build will fail.
