### ISSUE TITLE
Use subdirectories to name actions, e.g. zulip/github-actions-zulip/send-message

### ISSUE THREAD

**Issue by andersk** [zulip/github-actions-zulip#12]
I assume the intent of naming this repository github-actions-zulip is that we can put multiple actions here, but right now the send message action is referenced by just `zulip/github-actions-zulip`. We should rename it to `zulip/github-actions-zulip/send-message`, using the [subdirectory syntax](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory).

**Comment by ggrossetie** [comment]
I didn't know about the subdirectory syntax, neat 👌🏻 
We should probably remove the extra zulip no?

`zulip/github-actions/send-message`

**Comment by andersk** [comment]
Having `-zulip` in the repository name is nicer for people who want to fork it.

**Comment by timabbott** [comment]
Yeah, I agree with keeping `-zulip` in the name; it's really important for a repository that we expect to be forked to have its basename be globally unique.

**Comment by ggrossetie** [comment]
OK let's keep the `-zulip` suffix, I will move the send message action under a subdirectory named `send-message` 👍🏻

**Comment by ggrossetie** [comment]
However, I cannot find any "popular" GitHub Action using this pattern. So I wonder if it's a good idea.

- AWS is using a dedicated org: https://github.com/aws-actions
- Google Cloud is using a dedicated org: https://github.com/google-github-actions
- Azure has quite a few actions: https://github.com/marketplace?type=actions&query=Azure (they are not even using a specific naming convention, all GitHub Actions are in the Azure org)

Interestingly, Google Cloud has moved away from the sub-directory approach: https://github.com/google-github-actions/setup-gcloud/tree/master/upload-cloud-storage

Slack has only one action to send messages: https://github.com/slackapi/slack-github-action.
Not the official one but Discord has also only one action to send messages: https://github.com/Ilshidur/action-discord

**Comment by ggrossetie** [comment]
We should probably stick with the "one repository per GitHub Action" strategy.
I wonder if we should rename this repository: `github-actions-send-message-zulip`?

**Comment by andersk** [comment]
We shouldn’t just copy what other organizations do without a reason. We have a reason for wanting a single repository: fewer repositories to maintain.

GitHub’s own [codeql-action](https://github.com/github/codeql-action) is an example of a repository with multiple actions as subdirectories.

**Comment by timabbott** [comment]
Yeah, and I think there are other actions (like a Resolve Topic integration) that could be pretty interesting to add.

**Comment by ggrossetie** [comment]
> GitHub’s own codeql-action is an example of a repository with multiple actions as subdirectories.

This is a great example 👍🏻  
Interestingly, they are using a single `src`/`lib` directory at the root of the repository and each action (subdirectory) contains only a definition file (which references the `src`/`lib` directory):

- https://github.com/github/codeql-action/blob/main/analyze/action.yml
- https://github.com/github/codeql-action/tree/main/init/action.yml
- https://github.com/github/codeql-action/blob/main/autobuild/action.yml

I think it makes sense in our case since we will probably want to share some logic to interact with the Zulip API.

> We shouldn’t just copy what other organizations do without a reason. We have a reason for wanting a single repository: fewer repositories to maintain.

Using experience from others is a valid reason. Every solution has benefits and drawbacks.
For instance, one drawback is that we won't be able to release actions individually. We could argue that this is actually a good thing but only experience will tell (and this is where experience from others is important). 

I was a bit unsure since I wasn't able to find a single repository where this approach was taken.
But now I can clearly see the benefits in our context and how we will be able to manage the build/release workflow.

Let's proceed 😉
